### ISSUE TITLE
Help using Braintree with Xamarin

### ISSUE THREAD

**Issue by acolangelo86** [Clusterize/Xamarin-Braintree.iOS-Bindings#2]
Hi, I need help using Braintree with Xamarin. I have no idea how to add credit card and get nonce (I 'm able to create CardBuilder, but when I try to do Card.Tokenize(braintreeFragment, cardBuilder), I have no idea how to get Nonce from Braintree). Please help me.
Thanks

**Comment by nirinchev** [comment]
Hi, it seems you are using the android SDK, and this is a repo for the iOS bindings :) That being said, I think you need to [register a listener](https://developers.braintreepayments.com/guides/client-sdk/setup/android/v1#register-listeners) to collect the nonce.
