### ISSUE TITLE
Drop-in Ui not loading

### ISSUE THREAD

**Issue by shahbazsa** [Clusterize/Xamarin-Braintree.iOS-Bindings#3]
HI,
I am trying to use your binding to load braintree drop-in ui. I created dll and trying to use with below code in view controller, but loads nothing but a white screen. Any idea about the issue?

```
public override void ViewDidLoad()
		{
			base.ViewDidLoad();
			
				var controller = Braintree.Create(clientToken).CreateDropInViewController(new BTViewControllerDelegateClass(this));
				controller.FetchPaymentMethods();
				controller.SummaryTitle = "2 packs of dog food";
				controller.SummaryDescription = "Your dog will love it!";
				controller.DisplayAmount = "$45";
				controller.CallToActionText = "Buy now!";
				this.PresentViewController(controller, true, null);
			
		}
```

**Comment by nirinchev** [comment]
Hm, weird. Do you have any warnings/exceptions in the output that could help in narrowing it down?

**Comment by shahbazsa** [comment]
@nirinchev Thanks for the hint. I checked the output and found a warning. I moved the code to ViewDidAppear() and the drop in ui is loading. But one issue is that when i validate the card details, the onsuccess() or oncanceled() is not triggered in delegate implementation. Is this the known issue?

**Comment by nirinchev** [comment]
They should trigger, otherwise it would be impossible to obtain the nonce :) Can you paste your implementation of the delegate to see if I'll be able to figure out what's going on?

**Comment by shahbazsa** [comment]
@nirinchev  Please refer below code
Viewcontroller.cs 

```
public override void ViewDidAppear(bool animated)
		{
			base.ViewDidAppear(animated);

			var controller = Braintree.Create(clientToken).CreateDropInViewController(new BTViewControllerDelegateClass(this));

			controller.FetchPaymentMethods();
			controller.SummaryTitle = "2 packs of dog food";
			controller.SummaryDescription = "Your dog will love it!";
			controller.DisplayAmount = "$45";
			controller.CallToActionText = "Buy now!";
			this.PresentViewController(controller, true, null);
}
```

BTViewControllerDelegateClass.cs

```
public class BTViewControllerDelegateClass : BTDropInViewControllerDelegate
	{
		UIViewController viewController;

		public BTViewControllerDelegateClass(UIViewController viewController)
		{
			this.viewController = viewController;

		}

		public override void OnCanceled(BTDropInViewController controller)
		{
			throw new NotImplementedException();
		}

		public override void OnSuccess(BTDropInViewController controller, BTPaymentMethod paymentMethod)
		{
			throw new NotImplementedException();
		}
	}
```

**Comment by nirinchev** [comment]
Hm... seems like it should work just fine. Is the `clientToken` valid? We have a fairly similar code and the callbacks are getting called just fine.

**Comment by shahbazsa** [comment]
@nirinchev yes..the client token is valid as I can load drop in ui with card details. Do I need to implement any other interface in my view controller or any other parameter that i can check?

**Comment by nirinchev** [comment]
Okay, let's try one last thing - can you save the controller and the delegate to class-level variables. Something like:
```
public class MyController : UIViewController
{
  private BTViewControllerDelegateClass btDelegate;
  private BTDropInViewController btController;

  public override void ViewDidAppear(bool animated)
  {
    base.ViewDidAppear(animated);

    this.btDelegate = new BTViewControllerDelegateClass(this);
    this.btController = Braintree.Create(clientToken).CreateDropInViewController(this.btDelegate);
    // rest of init and present
  }
}
```

Obviously, if it works, you'll need to dispose, etc., but just as an experiment, let's see if it works. My guess is that the GC might be prematurely collecting stuff, but I may be mistaken.

**Comment by shahbazsa** [comment]
@nirinchev That worked!! Simply superb. I didn't realise that. Thanks again!
